name: Build

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Rust Tests
        run: cargo test --all-targets --locked ${{ runner.debug && '--verbose' || '' }}
      - name: TypeScript
        run: npm run type:check
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Clippy
        run: cargo clippy --no-deps --all-targets --locked ${{ runner.debug && '--verbose' || '' }}
      - name: Prettier
        run: npm run format:check
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build --bin=server --release --locked ${{ runner.debug && '--verbose' || '' }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            target/release/server
            public/
          if-no-files-found: error
