name: Rust build, test and clippy

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Cache rust target files
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-rust-target

    - run: sudo npm install -g sass
      
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose
