name: Rust build, test and clippy

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.2
    
    - name: Cache rust target files
      uses: actions/cache@v3.3.1
      with:
        path: target
        key: ${{ runner.os }}-rust-target

    - run: sudo npm install -g sass
      
    - name: Check
      run: cargo check --verbose --all-targets --locked
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose --no-deps --all-targets --locked
